In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
appearances = pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\appearances.csv")
clubs = pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\clubs.csv")
competitions = pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\competitions.csv")
games = pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\games.csv")
player_valuations = pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\player_valuations.csv")
players =  pd.read_csv("C:\\Users\\Gabriel Castillo\\Desktop\\GITHUB GABRIEL\\EDA\\EDATheBridge\\Futbol\\data\\players.csv")

In [4]:
appearances

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards,date,player_pretty_name
0,52453,2483937,2483937_52453,RU1,28095,0,0,90,0,0,2014-08-08,Haris Handzic
1,67064,2479929,2479929_67064,RU1,28095,0,0,90,0,0,2014-08-03,Felicio Brown Forbes
2,67064,2483937,2483937_67064,RU1,28095,0,0,90,0,0,2014-08-08,Felicio Brown Forbes
3,67064,2484582,2484582_67064,RU1,28095,0,0,55,0,0,2014-08-13,Felicio Brown Forbes
4,67064,2485965,2485965_67064,RU1,28095,0,0,90,0,0,2014-08-16,Felicio Brown Forbes
...,...,...,...,...,...,...,...,...,...,...,...,...
1072827,369552,3837232,3837232_369552,NL1,200,0,0,83,0,0,2022-08-20,Luuk Brouwers
1072828,369552,3837391,3837391_369552,NL1,200,0,0,78,0,0,2022-08-28,Luuk Brouwers
1072829,369552,3837395,3837395_369552,NL1,200,0,0,90,0,0,2022-09-02,Luuk Brouwers
1072830,369552,3839703,3839703_369552,NL1,200,0,0,45,0,0,2022-09-11,Luuk Brouwers
1072831,369552,3839707,3839707_369552,NL1,200,0,0,1,0,0,2022-09-16,Luuk Brouwers

In [5]:
appearances.shape

(1072832, 12)

In [6]:
appearances.columns

Index(['player_id', 'game_id', 'appearance_id', 'competition_id',
       'player_club_id', 'goals', 'assists', 'minutes_played', 'yellow_cards',
       'red_cards', 'date', 'player_pretty_name'],
      dtype='object')

In [7]:
clubs.columns

Index(['club_id', 'name', 'pretty_name', 'domestic_competition_id',
       'total_market_value', 'squad_size', 'average_age', 'foreigners_number',
       'foreigners_percentage', 'national_team_players', 'stadium_name',
       'stadium_seats', 'net_transfer_record', 'coach_name', 'url'],
      dtype='object')

In [8]:
games

,game_id,competition_code,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,stadium,attendance,referee,url,club_home_pretty_name,club_away_pretty_name,aggregate
0,2244388,SUC,2012,final 1st leg,2012-08-22,131,418,3,2,-1,-1,Camp Nou,91728,Carlos Clos GÃ³mez,https://www.transfermarkt.co.uk/spielbericht/i...,Fc Barcelona,Real Madrid,3:2
1,2219794,BESC,2011,Final,2012-07-22,58,498,3,2,-1,-1,Constant Vanden Stock Stadion,14485,Laurent Colemonts,https://www.transfermarkt.co.uk/spielbericht/i...,Rsc Anderlecht,Ksc Lokeren,3:2
2,2244389,SUC,2012,final 2nd leg,2012-08-29,418,131,2,1,-1,-1,Santiago BernabÃ©u,80000,MatÃ©u Lahoz,https://www.transfermarkt.co.uk/spielbericht/i...,Real Madrid,Fc Barcelona,2:1
3,2271112,DFB,2012,Round of 16,2012-12-18,48,60,0,1,-1,-1,BBBank Wildpark,28200,Dr. Jochen Drees,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,Sc Freiburg,0:1
4,2229332,DFL,2012,Final,2012-08-12,27,16,2,1,-1,-1,Allianz Arena,69000,Michael Weiner,https://www.transfermarkt.co.uk/spielbericht/i...,Fc Bayern Munchen,Borussia Dortmund,2:1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57765,3911792,CL,2022,Group C,2022-09-13,941,46,0,2,-1,-1,Doosan ArÃ©na,11252,Sandro SchÃ¤rer,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,Inter Mailand,0:2
57766,3901635,ECLQ,2022,Qualifying Round 2nd leg,2022-08-25,2976,40812,5,4,-1,-1,Toto Jacob Turner Stadium,14701,Erik Lambrechts,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,5:4
57767,3911795,CL,2022,Group D,2022-09-07,24,336,0,3,-1,-1,Deutsche Bank Park,50500,Orel Grinfeld,https://www.transfermarkt.co.uk/spielbericht/i...,Eintracht Frankfurt,Sporting Lissabon,0:3
57768,3911799,CL,2022,Group D,2022-09-07,148,244,2,0,-1,-1,Tottenham Hotspur Stadium,57367,Slavko Vincic,https://www.transfermarkt.co.uk/spielbericht/i...,Tottenham Hotspur,Olympique Marseille,2:0
57769,3911739,CL,2022,Group B,2022-09-13,15,13,2,0,-1,-1,BayArena,25825,Michael Oliver,https://www.transfermarkt.co.uk/spielbericht/i...,Bayer 04 Leverkusen,Atletico Madrid,2:0

In [9]:
games.shape

(57770, 18)

In [10]:
games.columns

Index(['game_id', 'competition_code', 'season', 'round', 'date',
       'home_club_id', 'away_club_id', 'home_club_goals', 'away_club_goals',
       'home_club_position', 'away_club_position', 'stadium', 'attendance',
       'referee', 'url', 'club_home_pretty_name', 'club_away_pretty_name',
       'aggregate'],
      dtype='object')

In [11]:
appearances

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards,date,player_pretty_name
0,52453,2483937,2483937_52453,RU1,28095,0,0,90,0,0,2014-08-08,Haris Handzic
1,67064,2479929,2479929_67064,RU1,28095,0,0,90,0,0,2014-08-03,Felicio Brown Forbes
2,67064,2483937,2483937_67064,RU1,28095,0,0,90,0,0,2014-08-08,Felicio Brown Forbes
3,67064,2484582,2484582_67064,RU1,28095,0,0,55,0,0,2014-08-13,Felicio Brown Forbes
4,67064,2485965,2485965_67064,RU1,28095,0,0,90,0,0,2014-08-16,Felicio Brown Forbes
...,...,...,...,...,...,...,...,...,...,...,...,...
1072827,369552,3837232,3837232_369552,NL1,200,0,0,83,0,0,2022-08-20,Luuk Brouwers
1072828,369552,3837391,3837391_369552,NL1,200,0,0,78,0,0,2022-08-28,Luuk Brouwers
1072829,369552,3837395,3837395_369552,NL1,200,0,0,90,0,0,2022-09-02,Luuk Brouwers
1072830,369552,3839703,3839703_369552,NL1,200,0,0,45,0,0,2022-09-11,Luuk Brouwers
1072831,369552,3839707,3839707_369552,NL1,200,0,0,1,0,0,2022-09-16,Luuk Brouwers

In [12]:
appearances[appearances["competition_id"]== "ES1"] 
# Â¿Se puede aÃ±adir una mascara a una mascara ya hecha?

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards,date,player_pretty_name
2494,74314,2475355,2475355_74314,ES1,993,0,0,90,0,0,2015-01-12,Edimar
2514,74314,2475365,2475365_74314,ES1,993,0,0,90,1,0,2015-01-16,Edimar
2515,74314,2475379,2475379_74314,ES1,993,0,0,90,0,0,2015-01-24,Edimar
2516,74314,2475383,2475383_74314,ES1,993,0,0,90,0,0,2015-01-31,Edimar
2517,74314,2475392,2475392_74314,ES1,993,0,0,90,0,0,2015-02-08,Edimar
...,...,...,...,...,...,...,...,...,...,...,...,...
1071073,229804,3885856,3885856_229804,ES1,681,0,0,19,0,0,2022-09-03,Aritz Elustondo
1071074,229804,3858325,3858325_229804,ES1,681,0,0,90,1,0,2022-09-18,Aritz Elustondo
1072662,372246,3844097,3844097_372246,ES1,1049,1,0,63,0,0,2022-08-14,Carlos Soler
1072663,372246,3844593,3844593_372246,ES1,1049,0,0,90,0,0,2022-08-21,Carlos Soler
1072664,372246,3885851,3885851_372246,ES1,1049,0,0,90,0,0,2022-08-29,Carlos Soler

In [6]:
appearances[appearances["player_id"]==26].head(25)

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards,date,player_pretty_name
129731,26,2460639,2460639_26,L1,16,0,0,90,0,0,2014-08-29,Roman Weidenfeller
129739,26,2460645,2460645_26,L1,16,0,0,90,0,0,2014-09-13,Roman Weidenfeller
129740,26,2460655,2460655_26,L1,16,0,0,90,0,0,2014-09-20,Roman Weidenfeller
129741,26,2460663,2460663_26,L1,16,0,0,90,0,0,2014-09-24,Roman Weidenfeller
129742,26,2460671,2460671_26,L1,16,0,0,90,0,0,2014-09-27,Roman Weidenfeller
129743,26,2460681,2460681_26,L1,16,0,0,90,0,0,2014-10-04,Roman Weidenfeller
129744,26,2460696,2460696_26,L1,16,0,0,90,0,0,2014-10-18,Roman Weidenfeller
129745,26,2460698,2460698_26,L1,16,0,0,90,0,0,2014-10-25,Roman Weidenfeller
129746,26,2460707,2460707_26,L1,16,0,0,90,0,0,2014-11-01,Roman Weidenfeller
129756,26,2460716,2460716_26,L1,16,0,0,90,0,0,2014-11-09,Roman Weidenfeller
129757,26,2460733,2460733_26,L1,16,0,0,90,0,0,2014-11-22,Roman Weidenfeller
129758,26,2460741,2460741_26,L1,16,0,0,90,0,0,2014-11-30,Roman Weidenfeller
129759,26,2460780,2460780_26,L1,16,0,0,90,0,0,2015-01-31,Roman Weidenfeller
129760,26,2460789,2460789_26,L1,16,0,0,90,0,0,2015-02-04,Roman Weidenfeller
129761,26,2460802,2460802_26,L1,16,0,0,90,0,0,2015-02-07,Roman Weidenfeller
129762,26,2460807,2460807_26,L1,16,0,0,90,0,0,2015-02-13,Roman Weidenfeller
129763,26,2460820,2460820_26,L1,16,0,0,90,0,0,2015-02-20,Roman Weidenfeller
129764,26,2460825,2460825_26,L1,16,0,0,90,0,0,2015-02-28,Roman Weidenfeller
129765,26,2460839,2460839_26,L1,16,0,0,90,0,0,2015-03-07,Roman Weidenfeller
129766,26,2460842,2460842_26,L1,16,0,0,90,0,0,2015-03-14,Roman Weidenfeller
129767,26,2460854,2460854_26,L1,16,0,0,90,0,0,2015-03-21,Roman Weidenfeller
129768,26,2460860,2460860_26,L1,16,0,0,90,0,0,2015-04-04,Roman Weidenfeller
129769,26,2460871,2460871_26,L1,16,0,0,90,0,0,2015-04-11,Roman Weidenfeller
129770,26,2460878,2460878_26,L1,16,0,0,90,0,0,2015-04-18,Roman Weidenfeller
129812,26,2460924,2460924_26,L1,16,0,0,90,0,0,2015-05-23,Roman Weidenfeller

In [14]:
players[players["pretty_name"].str.contains("Neymar")]

,player_id,last_season,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,...,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,agent_name,image_url,url,club_id,domestic_competition_id,club_name,club_pretty_name
25607,68290,2022,583,neymar,Neymar,Brazil,Brazil,1992-02-05,Attack,Left Winger,...,175,67500000.0,162000000.0,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/neymar/profil/...,583,FR1,fc-paris-saint-germain,Fc Paris Saint Germain

In [15]:
players[players["domestic_competition_id"]== "ES1"].head(20)

,player_id,last_season,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,...,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,agent_name,image_url,url,club_id,domestic_competition_id,club_name,club_pretty_name
4,30802,2013,3302,oscar-diaz,Oscar Diaz,Spain,Spain,1984-04-24,Attack,Centre-Forward,...,183,NaN,1080000.0,Pedro Bravo - Consulting,NaN,https://www.transfermarkt.co.uk/oscar-diaz/pro...,3302,ES1,ud-almeria,Ud Almeria
6,117549,2013,3302,rodri-rios,Rodri Rios,Spain,Spain,1990-06-06,Attack,Centre-Forward,...,174,270000.0,1800000.0,NaN,NaN,https://www.transfermarkt.co.uk/rodri-rios/pro...,3302,ES1,ud-almeria,Ud Almeria
7,186796,2013,3302,hicham-khaloua,Hicham Khaloua,Spain,Morocco,1995-05-07,Attack,Second Striker,...,174,360000.0,360000.0,ILUSION SPORT,NaN,https://www.transfermarkt.co.uk/hicham-khaloua...,3302,ES1,ud-almeria,Ud Almeria
135,29193,2013,3302,ruben-suarez,Ruben Suarez,Spain,Spain,1979-02-19,Attack,Second Striker,...,168,NaN,1350000.0,NaN,NaN,https://www.transfermarkt.co.uk/ruben-suarez/p...,3302,ES1,ud-almeria,Ud Almeria
136,173559,2013,3302,cristobal-gil,Cristobal Gil,Spain,Spain,1992-02-05,Attack,Attacking Midfield,...,171,135000.0,270000.0,NaN,NaN,https://www.transfermarkt.co.uk/cristobal-gil/...,3302,ES1,ud-almeria,Ud Almeria
138,35546,2013,3302,rafita,Rafita,Spain,Spain,1982-08-18,Defender,Right-Back,...,175,NaN,1080000.0,NaN,NaN,https://www.transfermarkt.co.uk/rafita/profil/...,3302,ES1,ud-almeria,Ud Almeria
139,76743,2013,3302,marcelo-silva,Marcelo Silva,Uruguay,Uruguay,1989-03-21,Defender,Centre-Back,...,185,270000.0,900000.0,NaN,NaN,https://www.transfermarkt.co.uk/marcelo-silva/...,3302,ES1,ud-almeria,Ud Almeria
140,72883,2013,3302,hans-martinez,Hans Martinez,Chile,Chile,1987-01-04,Defender,Centre-Back,...,178,135000.0,720000.0,NaN,NaN,https://www.transfermarkt.co.uk/hans-martinez/...,3302,ES1,ud-almeria,Ud Almeria
141,48294,2013,3302,bolano,Bolano,Spain,Spain,1985-10-15,Defender,Centre-Back,...,182,90000.0,1800000.0,Football Promotions (Scotland) Ltd.,NaN,https://www.transfermarkt.co.uk/bolano/profil/...,3302,ES1,ud-almeria,Ud Almeria
142,26801,2013,3302,hernan-pellerano,Hernan Pellerano,Argentina,Argentina,1984-06-04,Defender,Centre-Back,...,183,135000.0,3600000.0,DE 9 FÃšTBOL,NaN,https://www.transfermarkt.co.uk/hernan-pellera...,3302,ES1,ud-almeria,Ud Almeria
144,271446,2013,3302,kiutm,Kiutm,"Korea, South","Korea, South",1995-01-04,Attack,NaN,...,166,90000.0,270000.0,NaN,NaN,https://www.transfermarkt.co.uk/kiutm/profil/s...,3302,ES1,ud-almeria,Ud Almeria
145,3755,2013,3302,oscar-ustari,Oscar Ustari,Argentina,Argentina,1986-07-03,Goalkeeper,NaN,...,183,900000.0,6300000.0,Primotempo,NaN,https://www.transfermarkt.co.uk/oscar-ustari/p...,3302,ES1,ud-almeria,Ud Almeria
148,74561,2013,3302,victor-ibanez,Victor Ibanez,Spain,Spain,1989-04-21,Goalkeeper,NaN,...,191,158000.0,270000.0,Shuma PTE LTD,NaN,https://www.transfermarkt.co.uk/victor-ibanez/...,3302,ES1,ud-almeria,Ud Almeria
151,44072,2013,3302,marcos-tebar,Marcos Tebar,Spain,Spain,1986-02-07,Midfield,Defensive Midfield,...,185,NaN,1350000.0,NaN,NaN,https://www.transfermarkt.co.uk/marcos-tebar/p...,3302,ES1,ud-almeria,Ud Almeria
171,15974,2013,3302,esteban,Esteban,Spain,Spain,1975-06-27,Goalkeeper,NaN,...,177,NaN,2700000.0,NaN,NaN,https://www.transfermarkt.co.uk/esteban/profil...,3302,ES1,ud-almeria,Ud Almeria
1634,18416,2013,3368,aloys-nong,Aloys Nong,Cameroon,Cameroon,1983-10-16,Attack,Centre-Forward,...,180,NaN,1350000.0,FIFA-CO,NaN,https://www.transfermarkt.co.uk/aloys-nong/pro...,3368,ES1,ud-levante,Ud Levante
1636,29178,2013,331,nino,Nino,Spain,Spain,1980-06-10,Attack,Centre-Forward,...,169,NaN,3600000.0,YOU FIRST SPORTS,NaN,https://www.transfermarkt.co.uk/nino/profil/sp...,331,ES1,ca-osasuna,Ca Osasuna
1637,268708,2013,367,adrian-saballs,Adrian Saballs,Spain,Spain,1995-07-07,Attack,Centre-Forward,...,0,NaN,45000.0,NaN,NaN,https://www.transfermarkt.co.uk/adrian-saballs...,367,ES1,rayo-vallecano,Rayo Vallecano
1643,84133,2013,366,humberto-osorio,Humberto Osorio,Colombia,Colombia,1988-06-24,Attack,Centre-Forward,...,178,293000.0,1350000.0,NaN,NaN,https://www.transfermarkt.co.uk/humberto-osori...,366,ES1,real-valladolid,Real Valladolid
1644,297785,2013,366,zubi,Zubi,Spain,Spain,1993-05-21,Attack,Left Winger,...,181,NaN,NaN,NaN,NaN,https://www.transfermarkt.co.uk/zubi/profil/sp...,366,ES1,real-valladolid,Real Valladolid

In [16]:
players.shape

(25608, 21)

In [17]:
player_valuations

,player_id,date,market_value,datetime,dateweek,current_club_id,player_club_domestic_competition_id
0,254016,2013-07-22,90000,2013-07-22,2013-07-22,855,FR1
1,254016,2014-01-14,90000,2014-01-14,2014-01-13,855,FR1
2,51053,2008-08-25,90000,2008-08-25,2008-08-25,23,L1
3,51053,2011-05-30,90000,2011-05-30,2011-05-30,23,L1
4,51053,2011-08-26,225000,2011-08-26,2011-08-22,23,L1
...,...,...,...,...,...,...,...
368805,68290,2020-10-15,115200000,2020-10-15,2020-10-12,583,FR1
368806,68290,2021-04-09,99000000,2021-04-09,2021-04-05,583,FR1
368807,68290,2021-06-04,90000000,2021-06-04,2021-05-31,583,FR1
368808,68290,2021-12-16,81000000,2021-12-16,2021-12-13,583,FR1
368809,68290,2022-05-30,67500000,2022-05-30,2022-05-30,583,FR1

In [18]:
player_valuations.groupby("player_id")

In [19]:
player_valuations.shape

(368810, 7)

In [20]:
competitions

,competition_id,name,type,country_id,country_name,domestic_league_code,confederation,url,country_latitude,country_longitude
0,L1,bundesliga,first_tier,40,Germany,L1,europa,https://www.transfermarkt.co.uk/bundesliga/sta...,51.163818,10.447831
1,DFB,dfb-pokal,domestic_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfb-pokal/star...,51.163818,10.447831
2,DFL,dfl-supercup,domestic_super_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfl-supercup/s...,51.163818,10.447831
3,NL1,eredivisie,first_tier,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/eredivisie/sta...,52.243498,5.634323
4,NLP,toto-knvb-beker,domestic_cup,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/toto-knvb-beke...,52.243498,5.634323
5,NLSC,johan-cruijff-schaal,domestic_super_cup,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/johan-cruijff-...,52.243498,5.634323
6,BE1,jupiler-pro-league,first_tier,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/jupiler-pro-le...,50.640281,4.666715
7,BESC,belgian-supercup,domestic_super_cup,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/belgian-superc...,50.640281,4.666715
8,ES1,laliga,first_tier,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/laliga/startse...,39.326068,-4.837979
9,CDR,copa-del-rey,domestic_cup,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/copa-del-rey/s...,39.326068,-4.837979
10,SUC,supercopa,domestic_super_cup,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/supercopa/star...,39.326068,-4.837979
11,PO1,liga-portugal-bwin,first_tier,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/liga-portugal-...,39.662165,-8.135352
12,POCP,allianz-cup,domestic_cup,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/allianz-cup/st...,39.662165,-8.135352
13,POSU,supertaca-candido-de-oliveira,domestic_super_cup,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/supertaca-cand...,39.662165,-8.135352
14,FR1,ligue-1,first_tier,50,France,FR1,europa,https://www.transfermarkt.co.uk/ligue-1/starts...,46.603354,1.888334
15,FRCH,trophee-des-champions,domestic_super_cup,50,France,FR1,europa,https://www.transfermarkt.co.uk/trophee-des-ch...,46.603354,1.888334
16,GB1,premier-league,first_tier,189,England,GB1,europa,https://www.transfermarkt.co.uk/premier-league...,52.531021,-1.264906
17,CGB,efl-cup,domestic_cup,189,England,GB1,europa,https://www.transfermarkt.co.uk/efl-cup/starts...,52.531021,-1.264906
18,GBCS,community-shield,domestic_super_cup,189,England,GB1,europa,https://www.transfermarkt.co.uk/community-shie...,52.531021,-1.264906
19,RU1,premier-liga,first_tier,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/premier-liga/s...,64.686314,97.745306
20,RUP,russian-cup,domestic_cup,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-cup/st...,64.686314,97.745306
21,RUSS,russian-super-cup,domestic_super_cup,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-super-...,64.686314,97.745306
22,UKR1,premier-liga,first_tier,177,Ukraine,UKR1,europa,https://www.transfermarkt.co.uk/premier-liga/s...,49.487197,31.271832
23,UKRP,ukrainian-cup,domestic_cup,177,Ukraine,UKR1,europa,https://www.transfermarkt.co.uk/ukrainian-cup/...,49.487197,31.271832
24,UKRS,ukrainian-super-cup,domestic_super_cup,177,Ukraine,UKR1,europa,https://www.transfermarkt.co.uk/ukrainian-supe...,49.487197,31.271832
25,SC1,scottish-premiership,first_tier,190,Scotland,SC1,europa,https://www.transfermarkt.co.uk/scottish-premi...,56.786111,-4.114052
26,SFA,sfa-cup,domestic_cup,190,Scotland,SC1,europa,https://www.transfermarkt.co.uk/sfa-cup/starts...,56.786111,-4.114052
27,IT1,serie-a,first_tier,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/serie-a/starts...,42.638426,12.674297
28,CIT,italy-cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,42.638426,12.674297
29,SCI,supercoppa-italiana,domestic_super_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/supercoppa-ita...,42.638426,12.674297
30,GR1,super-league-1,first_tier,56,Greece,GR1,europa,https://www.transfermarkt.co.uk/super-league-1...,38.995368,21.987713
31,GRP,kypello-elladas,domestic_cup,56,Greece,GR1,europa,https://www.transfermarkt.co.uk/kypello-ellada...,38.995368,21.987713
32,TR1,super-lig,first_tier,174,Turkey,TR1,europa,https://www.transfermarkt.co.uk/super-lig/star...,38.959759,34.924965
33,DK1,superligaen,first_tier,39,Denmark,DK1,europa,https://www.transfermarkt.co.uk/superligaen/st...,55.670249,10.333328
34,DKP,sydbank-pokalen,domestic_cup,39,Denmark,DK1,europa,https://www.transfermarkt.co.uk/sydbank-pokale...,55.670249,10.333328
35,USC,uefa-super-cup,uefa_super_cup,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/uefa-super-cup...,46.314475,11.048029
36,CL,uefa-champions-league,uefa_champions_league,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/uefa-champions...,46.314475,11.048029
37,EL,europa-league,europa_league,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/europa-league/...,46.314475,11.048029
38,KLUB,fifa-klub-wm,fifa_club_world_cup,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/fifa-klub-wm/s...,46.314475,11.048029
39,ECLQ,uefa-europa-conference-league-qualifikation,uefa_europa_conference_league_qualifiers,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/uefa-europa-co...,46.314475,11.048029
40,CLQ,uefa-champions-league-qualifikation,uefa_champions_league_qualifying,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/uefa-champions...,46.314475,11.048029
41,ELQ,europa-league-qualifikation,europa_league_qualifying,-1,NaN,NaN,europa,https://www.transfermarkt.co.uk/europa-league-...,46.314475,11.048029

In [21]:
competitions.shape

(42, 10)

In [22]:
competitions.loc[8]

competition_id                                                        ES1
name                                                               laliga
type                                                           first_tier
country_id                                                            157
country_name                                                        Spain
domestic_league_code                                                  ES1
confederation                                                      europa
url                     https://www.transfermarkt.co.uk/laliga/startse...
country_latitude                                                39.326068
country_longitude                                               -4.837979
Name: 8, dtype: object

In [23]:
clubs.head(10)

,club_id,name,pretty_name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,url
0,1032,fc-reading,Fc Reading,GB1,33.66,26,25.9,12,46.2,6,Select Car Leasing Stadium,24161,+Â£8.37m,Brian McDermott,https://www.transfermarkt.co.uk/fc-reading/sta...
1,2323,orduspor,Orduspor,TR1,NaN,0,NaN,0,NaN,0,19 EylÃ¼l Stadyum,11024,+-0,HÃ©ctor CÃºper,https://www.transfermarkt.co.uk/orduspor/start...
2,1387,acn-siena-1904,Acn Siena 1904,IT1,4.32,30,26.2,6,20.0,2,Artemio Franchi,15373,Â£-6Th.,Serse Cosmi,https://www.transfermarkt.co.uk/acn-siena-1904...
3,1071,wigan-athletic,Wigan Athletic,GB1,12.38,29,26.5,14,48.3,6,DW Stadium,25133,Â£-140Th.,Roberto MartÃ­nez,https://www.transfermarkt.co.uk/wigan-athletic...
4,2703,spartak-vladikavkaz,Spartak Vladikavkaz,RU1,NaN,1,20.0,0,NaN,0,Republican Stadium Spartak,32464,+-0,Vladimir Gazzaev,https://www.transfermarkt.co.uk/spartak-vladik...
5,142,real-saragossa,Real Saragossa,ES1,22.86,24,26.6,5,20.8,0,La Romareda,33068,+-0,Manolo JimÃ©nez,https://www.transfermarkt.co.uk/real-saragossa...
6,566,beerschot-ac,Beerschot Ac,BE1,NaN,0,NaN,0,NaN,0,Olympisch Stadion,12771,+-0,Adrie Koster,https://www.transfermarkt.co.uk/beerschot-ac/s...
7,1436,sc-beira-mar,Sc Beira Mar,PO1,135.00,22,27.5,9,40.9,0,EstÃ¡dio MÃ¡rio Duarte,12000,+-0,Ulisses Morais,https://www.transfermarkt.co.uk/sc-beira-mar/s...
8,4750,sc-olhanense,Sc Olhanense,PO1,68.00,22,24.1,9,40.9,0,EstÃ¡dio JosÃ© Arcanjo,10080,+-0,Abel Xavier,https://www.transfermarkt.co.uk/sc-olhanense/s...
9,23,eintracht-braunschweig,Eintracht Braunschweig,L1,6.48,27,24.9,3,11.1,0,EINTRACHT-Stadion,23325,+-0,Torsten Lieberknecht,https://www.transfermarkt.co.uk/eintracht-brau...

In [24]:
clubs.shape

(410, 15)

In [25]:
clubs.groupby("domestic_competition_id").sum()

,club_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_seats
domestic_competition_id,,,,,,,,
BE1,129752,788.75,586,513.5,340,1213.9,120,374738
DK1,94061,270.47,479,433.6,200,750.4,59,256049
ES1,66428,4906.26,810,862.5,284,1131.1,176,1043480
FR1,51863,4083.51,924,855.4,461,1681.0,237,903171
GB1,27860,9723.19,928,919.4,562,2130.1,384,1230446
GR1,174312,405.90,668,617.7,321,1139.0,77,392064
IT1,65285,4874.85,1047,919.5,523,1794.2,283,1117140
L1,30471,3907.64,780,705.9,348,1251.9,193,1160752
NL1,17860,995.47,733,643.2,319,1176.0,94,485940
PO1,89757,1314.13,815,754.8,457,1632.6,96,488878
RU1,317932,773.93,651,649.7,144,557.9,93,968061
SC1,22634,325.93,421,409.5,218,816.3,66,290713
TR1,222833,1634.48,993,865.9,388,1320.1,137,961864
UKR1,625933,281.60,480,498.6,49,186.6,35,672695

In [26]:
clubs["domestic_competition_id"]=="ES1"

0      False
1      False
2      False
3      False
4      False
       ...
405    False
406    False
407    False
408    False
409    False
Name: domestic_competition_id, Length: 410, dtype: bool

In [27]:
clubs.loc[clubs["domestic_competition_id"]=="ES1"]

,club_id,name,pretty_name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,url
5,142,real-saragossa,Real Saragossa,ES1,22.86,24,26.6,5,20.8,0,La Romareda,33068,+-0,Manolo JimÃ©nez,https://www.transfermarkt.co.uk/real-saragossa...
26,993,fc-cordoba,Fc Cordoba,ES1,2.99,24,26.6,2,8.3,0,Nuevo ArcÃ¡ngel,21822,+Â£270Th.,Albert Ferrer,https://www.transfermarkt.co.uk/fc-cordoba/sta...
61,2448,sporting-gijon,Sporting Gijon,ES1,25.52,26,25.6,6,23.1,4,El MolinÃ³n - Enrique Castro Quini,30000,Â£-225Th.,Abelardo,https://www.transfermarkt.co.uk/sporting-gijon...
66,1084,fc-malaga,Fc Malaga,ES1,20.97,28,25.0,6,21.4,0,La Rosaleda,30044,+-0,MÃ­chel,https://www.transfermarkt.co.uk/fc-malaga/star...
75,897,deportivo-la-coruna,Deportivo La Coruna,ES1,6.95,24,26.2,3,12.5,0,Riazor,32912,+Â£1.53m,Pepe Mel,https://www.transfermarkt.co.uk/deportivo-la-c...
76,472,ud-las-palmas,Ud Las Palmas,ES1,20.70,27,25.9,6,22.2,1,Estadio de Gran Canaria,32400,+Â£1.30m,Manolo MÃ¡rquez,https://www.transfermarkt.co.uk/ud-las-palmas/...
106,1244,cd-leganes,Cd Leganes,ES1,32.85,28,27.5,8,28.6,3,Municipal de Butarque,12454,+Â£2.25m,Mauricio Pellegrino,https://www.transfermarkt.co.uk/cd-leganes/sta...
127,1533,sd-eibar,Sd Eibar,ES1,26.82,25,28.9,5,20.0,0,Ipurua,8164,Â£-3.69m,JosÃ© Luis Mendilibar,https://www.transfermarkt.co.uk/sd-eibar/start...
128,5358,sd-huesca,Sd Huesca,ES1,26.64,24,27.6,6,25.0,3,El Alcoraz,9128,+Â£4.14m,MÃ­chel,https://www.transfermarkt.co.uk/sd-huesca/star...
153,1108,deportivo-alaves,Deportivo Alaves,ES1,51.66,26,27.2,7,26.9,2,Mendizorrotza,19840,+Â£2.12m,Luis GarcÃ­a,https://www.transfermarkt.co.uk/deportivo-alav...
154,16795,fc-granada,Fc Granada,ES1,80.46,29,27.8,13,44.8,4,Nuevo Los CÃ¡rmenes,19336,Â£-12.11m,Aitor Karanka,https://www.transfermarkt.co.uk/fc-granada/sta...
159,3368,ud-levante,Ud Levante,ES1,66.51,28,28.5,9,32.1,4,Ciutat de ValÃ¨ncia,25354,Â£-1.13m,Mehdi Nafti,https://www.transfermarkt.co.uk/ud-levante/sta...
337,2687,fc-cadiz,Fc Cadiz,ES1,58.50,27,28.5,9,33.3,6,Nuevo Mirandilla,21094,Â£-6.21m,Sergio,https://www.transfermarkt.co.uk/fc-cadiz/start...
339,237,rcd-mallorca,Rcd Mallorca,ES1,64.44,26,27.3,15,60.0,10,Visit Mallorca Estadi,20500,Â£-8.73m,Javier Aguirre,https://www.transfermarkt.co.uk/rcd-mallorca/s...
340,367,rayo-vallecano,Rayo Vallecano,ES1,74.25,27,28.0,10,37.0,7,Campo de FÃºtbol de Vallecas,15105,Â£-10.17m,Andoni Iraola,https://www.transfermarkt.co.uk/rayo-vallecano...
342,12321,fc-girona,Fc Girona,ES1,82.44,26,25.8,9,34.6,1,Municipal de Montilivi,11286,Â£-4.05m,MÃ­chel,https://www.transfermarkt.co.uk/fc-girona/star...
343,714,espanyol-barcelona,Espanyol Barcelona,ES1,82.98,21,26.4,5,23.8,3,RCDE Stadium,40500,+Â£6.66m,Diego MartÃ­nez,https://www.transfermarkt.co.uk/espanyol-barce...
344,331,ca-osasuna,Ca Osasuna,ES1,111.60,24,27.6,5,20.8,2,El Sadar,23576,Â£-1.80m,Jagoba Arrasate,https://www.transfermarkt.co.uk/ca-osasuna/sta...
346,3709,fc-getafe,Fc Getafe,ES1,129.87,24,27.1,12,50.0,9,Coliseum Alfonso PÃ©rez,16800,Â£-675Th.,Quique SÃ¡nchez Flores,https://www.transfermarkt.co.uk/fc-getafe/star...
347,1049,fc-valencia,Fc Valencia,ES1,213.03,24,23.9,14,58.3,9,Mestalla,48600,+Â£37.89m,Gennaro Gattuso,https://www.transfermarkt.co.uk/fc-valencia/st...
348,940,celta-vigo,Celta Vigo,ES1,115.83,22,26.0,9,40.9,4,Abanca BalaÃ­dos,29000,Â£-3.60m,Eduardo Coudet,https://www.transfermarkt.co.uk/celta-vigo/sta...
349,621,athletic-bilbao,Athletic Bilbao,ES1,213.30,26,27.1,1,3.8,4,San MamÃ©s,53289,+-0,Ernesto Valverde,https://www.transfermarkt.co.uk/athletic-bilba...
352,1050,fc-villarreal,Fc Villarreal,ES1,324.18,25,27.8,11,44.0,10,La CerÃ¡mica,23500,+Â£12.71m,Unai Emery,https://www.transfermarkt.co.uk/fc-villarreal/...
353,13,atletico-madrid,Atletico Madrid,ES1,550.35,22,27.8,16,72.7,18,Civitas Metropolitano,68456,Â£-17.60m,Diego Simeone,https://www.transfermarkt.co.uk/atletico-madri...
354,131,fc-barcelona,Fc Barcelona,ES1,732.33,25,25.4,10,40.0,20,Spotify Camp Nou,99354,Â£-106.20m,Xavi,https://www.transfermarkt.co.uk/fc-barcelona/s...
355,366,real-valladolid,Real Valladolid,ES1,58.50,24,27.8,9,37.5,3,Nuevo JosÃ© Zorrilla,27618,Â£-3.87m,Pacheta,https://www.transfermarkt.co.uk/real-valladoli...
358,3302,ud-almeria,Ud Almeria,ES1,78.30,28,25.3,13,46.4,2,Power Horse Stadium,15274,Â£-15.30m,Rubi,https://www.transfermarkt.co.uk/ud-almeria/sta...
359,1531,fc-elche,Fc Elche,ES1,64.98,25,28.0,9,36.0,3,Manuel MartÃ­nez Valero,31388,Â£-6.71m,Francisco RodrÃ­guez,https://www.transfermarkt.co.uk/fc-elche/start...
360,150,real-betis-sevilla,Real Betis Sevilla,ES1,234.00,26,28.7,12,46.2,10,Benito VillamarÃ­n,59378,Â£-15.08m,Manuel Pellegrini,https://www.transfermarkt.co.uk/real-betis-sev...
364,418,real-madrid,Real Madrid,ES1,753.75,23,27.4,16,69.6,16,Santiago BernabÃ©u,81044,+Â£10.94m,Carlo Ancelotti,https://www.transfermarkt.co.uk/real-madrid/st...
372,368,fc-sevilla,Fc Sevilla,ES1,244.53,25,28.4,18,72.0,12,RamÃ³n SÃ¡nchez-PizjuÃ¡n,43883,+Â£57.15m,Julen Lopetegui,https://www.transfermarkt.co.uk/fc-sevilla/sta...
395,681,real-sociedad-san-sebastian,Real Sociedad San Sebastian,ES1,334.17,27,24.8,5,18.5,6,Reale Arena,39313,+Â£24.75m,Imanol Alguacil,https://www.transfermarkt.co.uk/real-sociedad-...

In [28]:
clubs.loc[clubs["domestic_competition_id"]=="ES1"].shape

(32, 15)

In [29]:
# players.groupby("player_pretty_name").sum()

In [30]:
# players.shape

In [31]:
# players.sort_values(by = ["player_pretty_name"], ascending=[True]).sum()

In [32]:

# players_goals = players.groupby(by=["competition_id", "player_club_id"]).count()["player_id"]
# players_goals

In [33]:
# games = pd.read_csv()

In [34]:
a = appearances.groupby("player_pretty_name")[["goals", "assists"]].sum().sort_values(by= "goals", ascending=False)
a

                          goals  assists
player_pretty_name
Robert Lewandowski          355       72
Lionel Messi                335      180
Cristiano Ronaldo           324       82
Luis Suarez                 246      114
Harry Kane                  231       55
...                         ...      ...
Lamine Diarra                 0        0
Lamine Ndao                   0        0
Landry Bonnefoi               0        0
Apostolos Apostolopoulos      0        0
 Alpha Bdul Razak             0        0

[18185 rows x 2 columns]